apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-postgres-config
data:
  POSTGRES_DB: "user_db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-profile-service-postgres-config
data:
  POSTGRES_DB: "user_profile_db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kyc-service-postgres-config
data:
  POSTGRES_DB: "kyc_db"
